### ISSUE TITLE
clarify files page

### ISSUE THREAD

**Issue by JanKoppe** [o2r-project/o2r-web-api#10]
The files page should mention that it is not a separate API function, but a description of a answer subset for view single job/compendium

**Comment by nuest** [comment]
@JanKoppe Do you remember what this was about? It's not clear to me from the issue text.

**Comment by nuest** [comment]
@JanKoppe could you quickly check if this is still relevant, please?

**Comment by JanKoppe** [comment]
This has already been described in the documentation and therefore is solved.
