### ISSUE TITLE
API endpoint for all publications of one author

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-web-api#12]
After logging in an author will be redirected to his landingpage. There, all of his own publications will be listed. Therefore an api endpoint is needed to list all publications of one author (including metadata for each publication).

**Comment by nuest** [comment]
`api/v1/compendium?author=<authorid>` should do it, right?

**Comment by JanKoppe** [comment]
Yes, that resource should probably be the right one. Though we haven't defined the user management at all so far. Implementation might take a while.

**Comment by nuest** [comment]
@jansule When do you need this?

For a first implementation, I'd say this is not restricted at all. We could also just use the ORCID for filtering:

`/api/v1/compendium?orcid=xxxx-xxxx-xxxx-xxxx`

- [ ] implement in o2r-muncher
- [ ] add documentation
