### ISSUE TITLE
API endpoint for user management

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-web-api#14]
## Endpoints

- `api/v1/user` > list all orcids
- `api/v1/user/<orcid>` > show orcid and name, if logged as admin also show level

## Features

- [x] list all users
- [x] change user level (admin only) via `PATCH` request

**Comment by nuest** [comment]
@JanKoppe I would add this to the bouncer microservice. Do you concur or do you see this in an independent component?

A really good bouncer surely knows all the names and the credibility (level) of his customers.

**Comment by JanKoppe** [comment]
Yes, bouncer would be the right place to do that.
