### ISSUE TITLE
Mime type for files

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-web-api#17]
Hello,
referring to the [API](http://o2r.info/o2r-web-api/files/) a file has the attributes **path**, **name** and **size**. Please also add the attribute **type** containing a **string** with the file's mime type. Folders should not have this attribute.

Best,
Jan

**Comment by JanKoppe** [comment]
I've started documenting this in #18. A PR for a implementation in muncher exists, though the code is extremely basic (recognition only based on file extension, not actual content).

We would need to properly define the mappings between file extension and reported MIME types. Right now scripts (e.g. R scripts) are reported as `application/octet-stream`, though interpreting them as `text/plain` would make much more sense.

**Comment by jansule** [comment]
Here is a list of files we want to display (for now; each bulletpoint should have its own MIME type):
  * svg
  * geotiff
  * all other image files which can be displayed via <img>
  * video files
  * audio files
  * .csv files
  * everything else will be displayed as plain/text
  * RData might be displayed differently

**Comment by nuest** [comment]
custom mime types can be configured in this file in the muncher: https://github.com/o2r-project/o2r-muncher/blob/master/config/custom-mime.json

**Comment by nuest** [comment]
@jansule Can you please check files from your list and clearly mark which ones do not work yet?

**Comment by jansule** [comment]
@nuest 
File types that have already been successfully tested:
  * all other image files which can be displayed via `<img>`
  * everything else will be displayed as plain/text

File types that not have been tested yet:
  * svg
  * geotiff
  * video files
  * audio files
  * .csv files
  * RData might be displayed differently

**Comment by nuest** [comment]
Mime types to be added (after offline discussion)

- [ ] RData
- [ ] csv

@jansule prepares an example compendium with all potentially relevant file types

- [ ] example compendium

**Comment by nuest** [comment]
@jansule Please update the list of files that have not been tested yet here. Thanks!

**Comment by nuest** [comment]
@jansule please update!
