### ISSUE TITLE
Add entry point

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-web-api#2]
See https://restful-api-design.readthedocs.org/en/latest/urls.html#entry-point

Should contain version, list of resources etc.

**Comment by JanKoppe** [comment]
2e51e31b6b29c989a5a800ee653aa2a59f897e19

**Comment by nuest** [comment]
Could you please add an example (naturally not complete yet) of how the reponse to `/api/v1` would look like? I.e. it should contain a list of the resources in json format, maybe listed as (both) "current" and with version, and some semantic name, so that a client would derive the actual resource urls from such a response.

**Comment by nuest** [comment]
fixed in https://github.com/nuest/o2r-muncher/commit/469efe19a32ef2829c02507d20e8168cf0f61eb9
