### ISSUE TITLE
API does not reflect session requirements

### ISSUE THREAD

**Issue by JanKoppe** [o2r-project/o2r-web-api#21]
With the new User authentication and authenticated sessions, a better user authentification has been implemented. This makes the current `X-API-Key` header obsolete. Endpoints requiring authenticated sessions should reflect this, which would (as of now) only be the `POST /api/v1/compendium` endpoint. Also, this needs further implementation in the o2r muncher service.

- [x]  Remove `X-API-Key` _from documentation_
- [x]  Implement authenticated session for `/api/v1/compendium` in o2r muncher - see https://github.com/o2r-project/o2r-muncher/issues/21
- [x]  Add note to API docs that an authenticated session is required for `/api/v1/compendium`

**Comment by nuest** [comment]
WIP @ https://github.com/nuest/o2r-muncher/tree/userlevels
