### ISSUE TITLE
Attribute Username

### ISSUE THREAD

**Issue by jansule** [o2r-project/o2r-web-api#28]
The `orcid id` has already been added to the metadata of a single compendium. It would be nice if also the `username` could be added. Maybe something like this?

```json
"User": {
    "name": "xy",
    "orcid": "1234"
}
```

**Comment by nuest** [comment]
I'd like to see a more complete list here first. Why not add the author affiliation, and a user icon?

I'd strongly favour to have only the user id and then retrieve all detailed information asynchronously from the user endpoint.

**Comment by jansule** [comment]
Alright. This seems to be the better solution.
