### ISSUE TITLE
Document metadata property of compendium

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-web-api#34]
The metadata part of the platform is still very much under development. Instead of putting an intermediate documentation into the API we will keep an updated version of the documentation in this issue, and also discuss it here.

Eventually this should go into a file `docs/compendium-metadata.md`

# Tasks

- [x] describe each field in `o2r` metadata <- edit: see schema for full description

# Compendium metadata

o2r provides seperate MD for different purposes making use of their translatability:

```json
{
   "id":"XyZ19",
   "metadata":{
      "third_party": {},
      "o2r": {
              "license": {},
       },
      "raw": {}
   },
   "created":"2016-12-15T08:22:27.029Z",
   "user":"0000-0002-0024-5046",
   "files":{
   }
}
```

## License metadata

edit: need license in main for mappings!
~~Licensing information is provided separately for the main parts of a compendium, i.e. data, text, and code. Cases such as different licenses for different files or sub-projects are _not_ covered directly.~~

License MD can contain free text or a list of licenses.

A license must be provided for each part of the compendium (code, data, text). The license might be identical. The license string is based on [Open Licenses Service](http://licenses.opendefinition.org/) names.

edit: need to look at repository requirements, cf. trello card
~~- for code, the [list of OSI licenses](http://licenses.opendefinition.org/licenses/groups/osi.json) is recommended~~
  - ~~an alternative list is [SPDX](https://spdx.org/licenses/)~~
- ~~for text, the [list of Open Definition licenses](http://licenses.opendefinition.org/licenses/groups/od.json) is recommended~~
- ~~for data, the list of [CKAN licenses](http://licenses.opendefinition.org/licenses/groups/ckan.json) is recommended~~

```json
{
   "metadata":{
      "license":{
         "data":"Against-DRM",
         "text":"CC-BY-4.0",
         "code":"AAL"
      }
   }
}
```

## o2r metadata

This subset contains a core set of metadata attributes. They are refined from automatic extraction ("raw MD) to comply to the [o2r-schema](https://github.com/o2r-project/o2r-meta/blob/master/schema/docs/o2r-schema.md). Within the workflow, the user of the o2r platform is to review the raw MD and provide additions or modifications. The MD broker will translate the corrected raw MD to o2r MD.

```json
{
   "metadata":{
      "o2r":{   "title":"ERC title", ... }
   }
}
```

edit: we dont need anythin beyond this point. e.g. zenodo MD is one subset of the `metadata` json key.

~~
## ~~Shipping metadata~~

~~This element contains recipient-specific metadata for shipments. It is derived from core metadata and updated after manual edits. It can directly be used for shipment purposes.~~

```json
{
   "metadata":{
      "shipping":{
         "zenodo":{

         },
         "orcid":{

         },
         "codemeta":{

         },
         "datacite":{

         }
      }
   }
}
```

**Comment by 7048730** [comment]
updated with edits
