### ISSUE TITLE
Clarification questions and comments

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-web-api#4]
- `in 01-API.md`
  - are "groups" equal to "service endpoints", or RESTish "resources"?
- `02-upload.md`
  - URC
    - suggest to just use `../compendium`, or do we want to distinguish URC, ERC, PERC? I am against modelling these states in the URLs
    - why not `/upload/urc/:id`, but content with JSON?
  - Workspace
    - should say something like "archived workspace", and support not just `zip`, but also `tar.gz`.
  - External source
    - something generic, e.g. `/upload/remote` with `POST` and then we figure out from the provided JSON payload what it is (e.g. git URL)
- `03-execution.md`
  - `execute_now` is very limited, why not a `delay_seconds` which is `0` by default? or easier, a `job_start_time`, which can be in the past (execute now) or in the future (the client has to do the math)
  - `FileDescriptor` should be marked a a _potential_ later feature
  - why not `/compendium/<compendium ID>/jobs`?
  - I find the `create` part in the URL confusing - isn't that what `POST` and `PUT` are for?
  - similar for `../run` - should this not be `POST` to `/jobs/:id`?
  - `/jobs/view/:id` should simply be `GET` `/jobs/:id`
- `04-ERC.md`
  - I am for using "compendium" in the text. 
  - `/erc/view/:id` > no need for `/view`
- `05-user.md`
  - good this is not started yet, we don't need users for now. 

- **General**
  - add an version element to the URL, i.e. `/v1/upload/...` etc.
  - introduce pagination to all responses that can contain more than one resource

**Comment by JanKoppe** [comment]
Addressed everything but external sources. I'd like to discuss this feature a bit more before proposing a structure. This will be continued in #8.
