### ISSUE TITLE
reconsider license

### ISSUE THREAD

**Issue by nuest** [o2r-project/o2r-web-api#5]
I am not sure Apache is a license that works for a specification, which essentially is a document, not software/code.

I'd suggest to switch to http://creativecommons.org/licenses/by/4.0/ but am open for opinions and links to useful resources on this matter.

(Note to self: OpenSearch uses a CC license: http://www.opensearch.org/Specifications/License)

**Comment by edzer** [comment]
Good thought.

**Comment by JanKoppe** [comment]
LGTM.

**Comment by JanKoppe** [comment]
Changed in 5477ceca21676e91d806eaef53a4feae2cf1fc4a
