### ISSUE TITLE
Where `[FileDescriptor]` allows overriding files from the ERC with files from a different execution Job or a different ERC

### ISSUE THREAD

**Issue by MarkusKonk** [o2r-project/o2r-web-api#7]
Where `[FileDescriptor]` allows overriding files from the ERC with files
from a different execution Job or a different ERC. 
[what? diese Funktionalität ist mir neu.] 
[jk: O3,4, User Stories 53-55] 
[MK: Ok, wenn ich die User Stories dazu nehme, ist das klarer, aber dann müsstest du hier noch genauer werden.]

**Comment by nuest** [comment]
Not relevant anymore, will revisit the "data exchange" idea when it's ready.
